### ISSUE TITLE
Seems to not work for me.

### ISSUE THREAD

**Issue by cjemorton** [standardnotes/syncing-server-js#36]
Any idea on what I'm doing wrong? It's probably something stupid simple, I'm overlooking.

Is there a way to completely disable DATADOG TRACER?

`{"message":"Server started on port 3000","level":"info","dd":{"service":"syncing-server-js","version":"1.0.0"}}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
DATADOG TRACER CONFIGURATION - {"date":"2021-01-23T05:10:52.643Z","os_name":"FreeBSD","os_version":"12.2-RELEASE","architecture":"x64","version":"0.29.1","lang":"nodejs","lang_version":"14.15.4","enabled":true,"service":"syncing-server-js","agent_url":"http://127.0.0.1:8126","agent_error":"Network error trying to reach the agent: connect ECONNREFUSED 127.0.0.1:8126","debug":false,"analytics_enabled":false,"sample_rate":1,"sampling_rules":[],"tags":{"service":"syncing-server-js","version":"1.0.0"},"dd_version":"1.0.0","log_injection_enabled":true,"runtime_metrics_enabled":false,"integrations_loaded":["fs","http","net","dns","express@4.17.1","winston@3.3.3","ioredis@4.19.4","aws-sdk@2.824.0","https","http2","mysql2"]}
DATADOG TRACER DIAGNOSTIC - Agent Error: Network error trying to reach the agent: connect ECONNREFUSED 127.0.0.1:8126
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND cache
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14)
^C
`

**Comment by valantur** [comment]
Yeah it seems that this version of the server isn't ready for production yet.

**Comment by cjemorton** [comment]
Yeah, disappointing. 

Oh well, I'll keep an eye on the project. If it looks like its getting any work done on it. I may pull in the changes and rebuild and try again. Hopefully its built being fully compatible with FreeBSD as that's the platform my infrastructure runs on.

**Comment by atmoio** [comment]
This server is still in development and not yet ready for self-hosting. See https://github.com/standardnotes/syncing-server instead.

Update: server has been ready for some time. You can self-host here: https://github.com/standardnotes/standalone
